version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: ethersphere/swarm:0.4.2
        environment:
          DATADIR: /data
          PASSWORD: password123
        command:
          - >
            --bzznetworkid=255
            --nosync
            --maxpeers=0
            --verbosity=4
            --httpaddr=0.0.0.0
            --nat=none
            --corsdomain=*
            --ws
            --wsaddr=0.0.0.0
            --wsorigins=*

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - deps
      - run:
          name: Setup
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "yarn.lock" }}
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Tests
          command: yarn lint && yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: '/tmp/test-reports/jest/results.xml'
      - store_test_results:
          path: /tmp/test-reports
