version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: ethersphere/swarm:0.4.2
        environment:
          DATADIR: /data
          PASSWORD: password123
        command:
          - >
            --nosync
            --maxpeers=0
            --verbosity=4
            --httpaddr=0.0.0.0
            --nat=none
            --corsdomain=*
            --ws
            --wsaddr=0.0.0.0
            --wsorigins=*

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Setup
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Project tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: '/tmp/test-reports/jest/results.xml'
      - store_test_results:
          path: /tmp/test-reports
